// Mocks generated by Mockito 5.4.6 from annotations
// in common/test/services/notification_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:common/src/models/network/network_failure.dart' as _i5;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:schedule/models/calendar_course.dart' as _i6;
import 'package:schedule/models/calendar_course_with_supplies.dart' as _i7;
import 'package:schedule/repository/calendar_course_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CalendarCourseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalendarCourseRepository extends _i1.Mock
    implements _i3.CalendarCourseRepository {
  MockCalendarCourseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.CalendarCourse>> addCalendarCourse(
          _i6.CalendarCourse? calendarCourse) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCalendarCourse,
          [calendarCourse],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.CalendarCourse>>.value(
                _FakeEither_0<_i5.Failure, _i6.CalendarCourse>(
          this,
          Invocation.method(
            #addCalendarCourse,
            [calendarCourse],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.CalendarCourse>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateCalendarCourse(
          _i6.CalendarCourse? calendarCourse) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCalendarCourse,
          [calendarCourse],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateCalendarCourse,
            [calendarCourse],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.CalendarCourse>>>
      fetchCalendarCourses() => (super.noSuchMethod(
            Invocation.method(
              #fetchCalendarCourses,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i6.CalendarCourse>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.CalendarCourse>>(
              this,
              Invocation.method(
                #fetchCalendarCourses,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.CalendarCourse>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteCalendarCourse(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCalendarCourse,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteCalendarCourse,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.CalendarCourseWithSupplies>>>
      getTomorrowCourses() => (super.noSuchMethod(
            Invocation.method(
              #getTomorrowCourses,
              [],
            ),
            returnValue: _i4.Future<
                _i2.Either<_i5.Failure,
                    List<_i7.CalendarCourseWithSupplies>>>.value(_FakeEither_0<
                _i5.Failure, List<_i7.CalendarCourseWithSupplies>>(
              this,
              Invocation.method(
                #getTomorrowCourses,
                [],
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure, List<_i7.CalendarCourseWithSupplies>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.CalendarCourseWithSupplies>>>
      getCoursesForDate(DateTime? date) => (super.noSuchMethod(
            Invocation.method(
              #getCoursesForDate,
              [date],
            ),
            returnValue: _i4.Future<
                _i2.Either<_i5.Failure,
                    List<_i7.CalendarCourseWithSupplies>>>.value(_FakeEither_0<
                _i5.Failure, List<_i7.CalendarCourseWithSupplies>>(
              this,
              Invocation.method(
                #getCoursesForDate,
                [date],
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure, List<_i7.CalendarCourseWithSupplies>>>);
}
