// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxWDnydlaml9_cNV1mBY4LONj8-vKDmKQ',
    appId: '1:851694236975:web:0378103c125179ed661dda',
    messagingSenderId: '851694236975',
    projectId: 'dansmonsac-51195',
    authDomain: 'dansmonsac-51195.firebaseapp.com',
    storageBucket: 'dansmonsac-51195.firebasestorage.app',
    measurementId: 'G-H9XEZBK3BM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAow-PnxAE-o5FFcy5ARqnHdQW9pnNQBy0',
    appId: '1:851694236975:android:e3ee2f2097b88587661dda',
    messagingSenderId: '851694236975',
    projectId: 'dansmonsac-51195',
    storageBucket: 'dansmonsac-51195.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCygguKReKXXryeRNAD6QmWEo8T4CtUXdg',
    appId: '1:851694236975:ios:7e20f5ed1ec6bb79661dda',
    messagingSenderId: '851694236975',
    projectId: 'dansmonsac-51195',
    storageBucket: 'dansmonsac-51195.firebasestorage.app',
    iosBundleId: 'fr.kappsmobile.dansmonsac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCygguKReKXXryeRNAD6QmWEo8T4CtUXdg',
    appId: '1:851694236975:ios:7e20f5ed1ec6bb79661dda',
    messagingSenderId: '851694236975',
    projectId: 'dansmonsac-51195',
    storageBucket: 'dansmonsac-51195.firebasestorage.app',
    iosBundleId: 'fr.kappsmobile.dansmonsac',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxWDnydlaml9_cNV1mBY4LONj8-vKDmKQ',
    appId: '1:851694236975:web:175e97de44f6e62a661dda',
    messagingSenderId: '851694236975',
    projectId: 'dansmonsac-51195',
    authDomain: 'dansmonsac-51195.firebaseapp.com',
    storageBucket: 'dansmonsac-51195.firebasestorage.app',
    measurementId: 'G-0K1W52YGE6',
  );
}
