include: package:flutter_lints/flutter.yaml

linter:
  rules:
    implementation_imports: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_dependency: ignore
